import React from 'react';
import { X } from 'lucide-react';

interface AboutModalProps {
  isOpen: boolean;
  onClose: () => void;
  onApply: () => void;
}

export const AboutModal: React.FC<AboutModalProps> = ({ isOpen, onClose, onApply }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-[#14110E]/70 backdrop-blur-xs">
      <div 
        className="relative w-full max-w-2xl bg-[#FAF7F2] border border-[#D8D0C3] shadow-2xl overflow-hidden my-auto"
        role="dialog"
        aria-modal="true"
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#E3DACB] bg-[#F4EFE6]/60">
          <div className="flex items-center gap-2 text-[10px] font-typewriter tracking-widest text-[#78716C] uppercase">
            <span className="w-1.5 h-1.5 rounded-full bg-[#72272B]" />
            <span>ORIGIN & PHILOSOPHY · SIRF COFFEE</span>
          </div>
          <button
            onClick={onClose}
            className="text-[#78716C] hover:text-[#1C1917] p-1 transition-colors"
            aria-label="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-6 sm:p-10 max-h-[80vh] overflow-y-auto space-y-6">
          <div>
            <span className="text-[11px] font-typewriter uppercase tracking-widest text-[#72272B] block mb-2">
              FOUNDING ETHOS
            </span>
            <h3 className="text-3xl font-editorial font-light text-[#1C1917]">
              An alternative to the endless scroll.
            </h3>
          </div>

          <div className="space-y-4 text-xs font-typewriter text-[#44403C] leading-relaxed border-t border-[#E3DACB] pt-6">
            <p>
              Sirf Coffee was conceived around a very simple observation: modern dating platforms treat human beings as infinite digital catalog items, while traditional arrangements often bypass personal resonance and modern ambition.
            </p>
            <p>
              We wanted something different. An experience rooted in the time when someone who understood you personally would say: <em className="text-[#1C1917]">“I know someone you really should meet.”</em>
            </p>
            <p>
              Today, our small, dedicated team of curators works across continents—helping professionals, founders, academics, and creatives find partners who match not merely on paper, but in sensibility, cadence, and heart.
            </p>
          </div>

          <div className="border border-[#E3DACB] p-5 bg-white">
            <div className="text-[10px] font-typewriter uppercase tracking-widest text-[#78716C] mb-2">
              THE THREE TENETS
            </div>
            <ul className="space-y-2 text-xs font-typewriter text-[#1C1917]">
              <li className="flex items-start gap-2">
                <span className="text-[#72272B] font-bold">—</span>
                <span><strong>Human Curation:</strong> No recommendation is ever generated by machine algorithms.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#72272B] font-bold">—</span>
                <span><strong>Absolute Privacy:</strong> Your name and identity remain private until an introduction is mutually accepted.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#72272B] font-bold">—</span>
                <span><strong>Thoughtful Pacing:</strong> We favor one meaningful date over thirty meaningless chats.</span>
              </li>
            </ul>
          </div>

          <div className="flex items-center justify-between pt-6 border-t border-[#E3DACB]">
            <button
              onClick={onClose}
              className="text-xs font-typewriter tracking-wider uppercase text-[#78716C] hover:text-[#1C1917]"
            >
              Close
            </button>
            <button
              onClick={() => {
                onClose();
                onApply();
              }}
              className="px-6 py-2.5 text-xs font-typewriter tracking-widest uppercase text-[#FAF7F2] bg-[#1C1917] hover:bg-[#72272B] transition-colors"
            >
              Apply to Sirf Coffee →
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
